### ISSUE TITLE
关于数据集划分测试集和训练集的问题

### ISSUE THREAD

**Issue by wuxian0** [huangsuj/AWDR#1]
[AWDR](https://github.com/huangsuj/AWDR/tree/main)/[ops_al](https://github.com/huangsuj/AWDR/tree/main/ops_al)
/fsClassificaiton_WReg.m
关于：AWDR/ops_al/fsClassification_WReg.m中4-17行实现训练集和测试集划分。
以100Leaves数据集为例，1600个样本共有3个视图，每个视图有64个特征。
我的疑惑是 您的代码中划分操作直接对所有样本进行，这样不会存在训练过程中某个class未训练到么，又或者某个class全部被用来训练，测试中无法验证。
划分时是否需要在每个样本中按照比例均匀划分？

**Comment by huangsuj** [comment]
感谢您的来信，我们是按照原文对AWDR进行了复现，确实存在您提出的这个问题。针对这个问题，我们将对代码进行改进，比如取10%用做训练集时，将从每一类中都选择该类总数的0.1加入到训练集中。



在 2023-07-26 09:30:08，"wuxian0" ***@***.***> 写道：

AWDR/ops_al
/fsClassificaiton_WReg.m
关于：AWDR/ops_al/fsClassification_WReg.m中4-17行实现训练集和测试集划分。
以100Leaves数据集为例，1600个样本共有3个视图，每个视图有64个特征。
我的疑惑是 您的代码中划分操作直接对所有样本进行，这样不会存在训练过程中某个class未训练到么，又或者某个class全部被用来训练，测试中无法验证。
划分时是否需要在每个样本中按照比例均匀划分？

**Comment by wuxian0** [comment]
关于ε-dragging还有个问题请教。我在复现一篇其他文章，两篇文章优化过程有类似的地方，里面也使用了ε-dragging，但是这个 XW-Y 的值比较大，导致M有时候是0，有时候非常大，请问您在复现过程中有遇到过吗，大概会是哪的问题

谢谢

**Comment by wuxian0** [comment]
有个问题请教。我在初始化W b时 使用ops_al/least_squares_regression.m，对应的数据集是100Leaves，得到的WX+b-Y 残差很大，但使用数据集MSRC时得到的就是正常的，您是否遇到过这种情况，是需要对数据集做什么预处理吗
